### ISSUE TITLE
Marketing - Guide de comm / templates

### ISSUE THREAD

**Issue by ReyMyriam** [C-Super/appY-Documentation#83]

**Comment by pr0l0g** [comment]
- [ ] Flockage Bus 
- [ ] Guideline TikTok
- [ ] Guideline Print
- [ ] Guideline Merch
- [ ] Guideline Event/Show
- [ ] Guideline Invitations Emissions 
- [ ] Guideline Display/RS
- [ ] Opportunités futures (!!!)
